NAME	= push_swap

CC	= cc
FLAGS	= -Wall -Wextra -Werror

SOURCES	=	rules/ft_push.c \
		rules/ft_reverse.c \
		rules/ft_rotate.c \
		rules/ft_swap.c \
		sorting/ft_sort_3_numbers.c \
		sorting/ft_sort_5_numbers.c \
		sorting/ft_beyond_5.c \
		utils/utils1.c \
		utils/utils2.c \
		utils/utils3.c \













OBJECTS	= $(SOURCES:.c=.o)

$(NAME):
